!
!  MCLIB_Utilities_GPU.F90
!
!  Free-Format Fortran Source File
!  Generated by PGI Visual Fortran(R)
!  10/17/2017 10:06:52 PM
module MCMF_Utilities_GPU

  use cudafor
  use MCMF_CONSTANTS_GPU
  use MCMF_UTILITIES_FORMER
  use MCMF_TYPEDEF_ACLUSTER
  use CudaRandomC2F_M
  #ifdef MC_PROFILING
  use MCLIB_TimeProfile
  #endif
  implicit none

  !-----------------------
  interface AllocateArray_GPU
    MODULE PROCEDURE AllocateOneDimi_GPU
    MODULE PROCEDURE AllocateOneDimr_GPU
    MODULE PROCEDURE AllocateOneDimd_GPU
    MODULE PROCEDURE AllocateOneDimACluster_GPU


    MODULE PROCEDURE AllocateTwoDimi_GPU
    MODULE PROCEDURE AllocateTwoDimr_GPU
    MODULE PROCEDURE AllocateTwoDimd_GPU
    MODULE PROCEDURE AllocateTwoDimACluster_GPU

    MODULE PROCEDURE AllocateThreeDimi_GPU
    MODULE PROCEDURE AllocateThreeDimr_GPU
    MODULE PROCEDURE AllocateThreeDimd_GPU

  end interface AllocateArray_GPU

  !------------------
  interface DeAllocateArray_GPU
    MODULE PROCEDURE DeAllocateOneDimi_GPU
    MODULE PROCEDURE DeAllocateOneDimr_GPU
    MODULE PROCEDURE DeAllocateOneDimd_GPU
    MODULE PROCEDURE DeAllocateOneDimACluster_GPU

    MODULE PROCEDURE DeAllocateTwoDimi_GPU
    MODULE PROCEDURE DeAllocateTwoDimr_GPU
    MODULE PROCEDURE DeAllocateTwoDimd_GPU
    MODULE PROCEDURE DeAllocateTwoDimACluster_GPU

    MODULE PROCEDURE DeAllocateThreeDimi_GPU
    MODULE PROCEDURE DeAllocateThreeDimr_GPU
    MODULE PROCEDURE DeAllocateThreeDimd_GPU

  end interface DeAllocateArray_GPU


  contains

  !****************************************************
  subroutine Get_DeviceMemInfo(FreeMemSize,TotalMemSize)
    implicit none
    !---Dummy Vars---
    integer(kind=cuda_count_kind)::FreeMemSize
    integer(kind=cuda_count_kind)::TotalMemSize
    !---Local Vars---
    integer::err
    !---Body----
    err = cudaMemGetInfo(FreeMemSize,TotalMemSize)

    return
  end subroutine Get_DeviceMemInfo


  !*************************************************************
  subroutine AllocateOneDimi_GPU(Array,Length,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:),allocatable::Array
    integer,intent(in)::Length
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateOneDimi_GPU(Array,Name)

    if(Length .GT. 0) then
        allocate(Array(Length),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateOneDimi_GPU

  !*************************************************************
  subroutine AllocateOneDimr_GPU(Array,Length,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:),allocatable::Array
    integer,intent(in)::Length
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateOneDimr_GPU(Array,Name)

    if(Length .GT. 0) then
        allocate(Array(Length),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
         end if
    end if

    return
  end subroutine AllocateOneDimr_GPU

  !*************************************************************
  subroutine AllocateOneDimd_GPU(Array,Length,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:),allocatable::Array
    integer,intent(in)::Length
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateOneDimd_GPU(Array,Name)

    if(Length .GT. 0) then
        allocate(Array(Length),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateOneDimd_GPU

  !*************************************************************
  subroutine AllocateOneDimACluster_GPU(Array,Length,Name)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:),allocatable::Array
    integer,intent(in)::Length
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateOneDimACluster_GPU(Array,Name)

    if(Length .GT. 0) then
        allocate(Array(Length),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateOneDimACluster_GPU

  !*************************************************************
  subroutine AllocateTwoDimi_GPU(Array,LengthX,LengthY,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateTwoDimi_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0) then
        allocate(Array(LengthX,LengthY),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
         end if
    end if

    return
  end subroutine AllocateTwoDimi_GPU

  !*************************************************************
  subroutine AllocateTwoDimr_GPU(Array,LengthX,LengthY,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateTwoDimr_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0) then
        allocate(Array(LengthX,LengthY),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateTwoDimr_GPU

  !*************************************************************
  subroutine AllocateTwoDimd_GPU(Array,LengthX,LengthY,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateTwoDimd_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0) then
        allocate(Array(LengthX,LengthY),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateTwoDimd_GPU

  !*************************************************************
  subroutine AllocateTwoDimACluster_GPU(Array,LengthX,LengthY,Name)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateTwoDimACluster_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0) then
        allocate(Array(LengthX,LengthY),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateTwoDimACluster_GPU


  !*************************************************************
  subroutine AllocateThreeDimi_GPU(Array,LengthX,LengthY,LengthZ,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:,:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    integer,intent(in)::LengthZ
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateThreeDimi_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0 .AND. LengthZ .GT. 0) then
        allocate(Array(LengthX,LengthY,LengthZ),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateThreeDimi_GPU

  !*************************************************************
  subroutine AllocateThreeDimr_GPU(Array,LengthX,LengthY,LengthZ,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:,:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    integer,intent(in)::LengthZ
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateThreeDimr_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0 .AND. LengthZ .GT. 0) then
        allocate(Array(LengthX,LengthY,LengthZ),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateThreeDimr_GPU

  !*************************************************************
  subroutine AllocateThreeDimd_GPU(Array,LengthX,LengthY,LengthZ,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:,:,:),allocatable::Array
    integer,intent(in)::LengthX
    integer,intent(in)::LengthY
    integer,intent(in)::LengthZ
    character(*)::Name
    !---Dummy Vars---
    integer::istat
    !---Body---
    call DeAllocateThreeDimd_GPU(Array,Name)

    if(LengthX .GT. 0 .AND. LengthY .GT. 0 .AND. LengthZ .GT. 0) then
        allocate(Array(LengthX,LengthY,LengthZ),STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"allocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine AllocateThreeDimd_GPU

  !*************************************************************
  subroutine DeAllocateOneDimi_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateOneDimi_GPU


  !*************************************************************
  subroutine DeAllocateOneDimr_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateOneDimr_GPU

  !*************************************************************
  subroutine DeAllocateOneDimd_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateOneDimd_GPU

  !*************************************************************
  subroutine DeAllocateOneDimACluster_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateOneDimACluster_GPU

  !*************************************************************
  subroutine DeAllocateTwoDimi_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateTwoDimi_GPU

  !*************************************************************
  subroutine DeAllocateTwoDimr_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateTwoDimr_GPU

  !*************************************************************
  subroutine DeAllocateTwoDimd_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateTwoDimd_GPU

  !*************************************************************
  subroutine DeAllocateTwoDimACluster_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateTwoDimACluster_GPU



  !*************************************************************
  subroutine DeAllocateThreeDimi_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    integer,device,dimension(:,:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateThreeDimi_GPU

  !*************************************************************
  subroutine DeAllocateThreeDimr_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCSF),device,dimension(:,:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateThreeDimr_GPU

  !*************************************************************
  subroutine DeAllocateThreeDimd_GPU(Array,Name)
    implicit none
    !---Dummy Vars---
    real(kind=KMCDF),device,dimension(:,:,:),allocatable::Array
    character(*)::Name
    !---Local Vars---
    integer::istat
    !---Body---

    if(allocated(Array)) then
        deallocate(Array,STAT=istat)
        if(istat /=0) then
            write(*,*) "MCPSCUERROR: The Array :",Name,"Deallocate Failed !"
            pause
            stop
        end if
    end if

    return
  end subroutine DeAllocateThreeDimd_GPU

  !**********************************************************************
  attributes(device) function BinarySearch_GE_DEV(InputNum,DimensionX,TheArray,IndexX,LeftBound,RightBound) result(ResultIndex)
    implicit none
    !---Dummy Vars---
    integer,value,intent(in)::InputNum
    integer,value::DimensionX
    integer,device::TheArray(DimensionX,*) ! When the nollvm compiler option is used, the attributes(device) dummy vars array should write as (x,*) for two dimension, cannot be (:,:)
    integer,value::IndexX
    integer,value,intent(in)::LeftBound
    integer,value,intent(in)::RightBound
    integer,value,intent(out)::ResultIndex
    !---Local Vars---
    integer::ILeft,IRight,IMiddle
    !---Body---
    ResultIndex = -1

    ILeft = LeftBound
    IRight = RightBound

    DO While(ILeft .LE. IRight)

        IMiddle = (ILeft+IRight)/2

        if(InputNum .LE. TheArray(IndexX,IMiddle)) then
            if(IMiddle .eq. LeftBound .or. InputNum .GT. TheArray(IndexX,IMiddle-1) ) then
                ResultIndex = IMiddle
                exit
            else
                IRight = IMiddle - 1
                cycle
            end if
        else
            ILeft = IMiddle + 1
        end if

    END DO

    return
  end function BinarySearch_GE_DEV

  !*****************************************************
  attributes(device) function BinarySearch_EQ_DEV(InputNum,TheArray,LeftBound,RightBound) result(ResultIndex)
    implicit none
    !---Dummy Vars---
    integer,value,intent(in)::InputNum
    integer,device::TheArray(*) ! When the nollvm compiler option is used, the attributes(device) dummy vars array should write as (*) for one dimension,cannot be (:)
    integer,value,intent(in)::LeftBound
    integer,value,intent(in)::RightBound
    integer,value,intent(out)::ResultIndex
    !---Local Vars---
    integer::ILeft,IRight,IMiddle
    !---Body---
    ResultIndex = -1

    ILeft = LeftBound
    IRight = RightBound

    DO While(ILeft .LE. IRight)
        IMiddle = (ILeft+IRight)/2

        if(InputNum .LT. TheArray(IMiddle)) then
            IRight = IMiddle - 1
        else if(InputNum .GT. TheArray(IMiddle)) then
            ILeft = IMiddle + 1
        else
            ResultIndex = IMiddle
            exit
        end if

    END DO

    return
  end function BinarySearch_EQ_DEV

  !********************************************************
  attributes(device) subroutine BinarySearchBoxIndex(MultiBox,SearchIndex,Dev_SEIndexBox,ResultBoxIndex)
    implicit none
    !---Dummy Vars---
    integer, value::MultiBox
    integer, value::SearchIndex
    integer, device, dimension(MultiBox,2)::Dev_SEIndexBox
    integer,intent(out)::ResultBoxIndex
    !---Local Vars---
    integer::I,ILeft,IRight,IMiddle
    !---Body---
    ILeft = 1
    IRight = MultiBox
    IMiddle = (ILeft+IRight)/2

    DO I = 1,MultiBox
        if(Dev_SEIndexBox(IMiddle,1) .GT. SearchIndex) then
            IRight = IMiddle
            IMiddle = (ILeft + IMiddle)/2
            cycle
        else if(Dev_SEIndexBox(IMiddle,1) .LT. SearchIndex) then
            if(Dev_SEIndexBox(IMiddle,2) .GE. SearchIndex) then
                ResultBoxIndex = IMiddle
                exit
            else if(Dev_SEIndexBox(IMiddle,2) .LT. SearchIndex) then
              if(Dev_SEIndexBox(IMiddle+1,2) .GE. SearchIndex) then
                ResultBoxIndex = IMiddle + 1
                exit
              end if
              ILeft = IMiddle
              IMiddle = (IMiddle + IRight)/2
              cycle
            end if
        else
            ResultBoxIndex = IMiddle
            exit
        end if
    END DO

    ResultBoxIndex = min(ResultBoxIndex,MultiBox)

    return
  end subroutine BinarySearchBoxIndex

  !********************************************************
  attributes(device) subroutine BinarySearchBoxIndex2(MultiBox,SearchIndex,Dev_StartIndexBox,ResultBoxIndex)
    implicit none
    !---Dummy Vars---
    integer, value::MultiBox
    integer, value::SearchIndex
    integer, device, dimension(MultiBox)::Dev_StartIndexBox
    integer, intent(out)::ResultBoxIndex
    !---Local Vars---
    integer::I,ILeft,IRight,IMiddle
    !---Body---
    ResultBoxIndex = 1
    ILeft = 1
    IRight = MultiBox
    IMiddle = (ILeft+IRight)/2
    DO I = 1,MultiBox-1
        if(Dev_StartIndexBox(IMiddle) .GT. SearchIndex) then
            IRight = IMiddle
            IMiddle = (ILeft + IRight)/2
            cycle
        else if(Dev_StartIndexBox(IMiddle+1) .GT. SearchIndex) then
            ResultBoxIndex = IMiddle
            exit
        else if(IMiddle .eq. (MultiBox -1)) then
            ResultBoxIndex = MultiBox
            exit
        end if
        ILeft = IMiddle
        IMiddle = (IMiddle + IRight)/2
    END DO


  end subroutine BinarySearchBoxIndex2

  !*****************************************************************
  subroutine copyClustersDevToDevSync(Source_Clusters,Dest_Clusters,NC)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:),allocatable,target::Source_Clusters
    type(ACluster),device,dimension(:),allocatable::Dest_Clusters
    integer::NC
    !---Local Vars---
    type(C_DEVPTR)::SrP_Clusters
    type(C_DEVPTR)::DestP_Cluster
    integer::err
    !---Body---
    SrP_Clusters = c_devloc(Source_Clusters)
    DestP_Cluster = c_devloc(Dest_Clusters)


        if(NC .GT. size(Source_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of source clusters:",size(Source_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dest_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of destination clusters:",size(Dest_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if


    err = cudaMemCpy(DestP_Cluster,SrP_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToDevice)

    return
  end subroutine copyClustersDevToDevSync

  !*****************************************************************
  subroutine copyClustersDevToDevSync2D(Source_Clusters,Dest_Clusters,NC)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:,:),allocatable,target::Source_Clusters
    type(ACluster),device,dimension(:,:),allocatable::Dest_Clusters
    integer::NC
    !---Local Vars---
    type(C_DEVPTR)::SrP_Clusters
    type(C_DEVPTR)::DestP_Cluster
    integer::err
    !---Body---
    SrP_Clusters = c_devloc(Source_Clusters)
    DestP_Cluster = c_devloc(Dest_Clusters)


        if(NC .GT. size(Source_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of source clusters:",size(Source_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dest_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of destination clusters:",size(Dest_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if


    err = cudaMemCpy(DestP_Cluster,SrP_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToDevice)

    return
  end subroutine copyClustersDevToDevSync2D

  !*****************************************************************
  subroutine copyClustersDevToDevAsync(Source_Clusters,Dest_Clusters)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:),allocatable,target::Source_Clusters
    type(ACluster),device,dimension(:),allocatable::Dest_Clusters
    integer::NC
    !---Local Vars---
    type(C_DEVPTR)::SrP_Clusters
    type(C_DEVPTR)::DestP_Cluster
    integer::err
    !---Body---
    SrP_Clusters = c_devloc(Source_Clusters)
    DestP_Cluster = c_devloc(Dest_Clusters)


        if(NC .GT. size(Source_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of source clusters:",size(Source_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dest_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of destination clusters:",size(Dest_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if


    err = cudaMemCpyAsync(DestP_Cluster,SrP_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToDevice)

    return
  end subroutine copyClustersDevToDevAsync

  !*****************************************************************
  subroutine copyClustersDevToDevAsync2D(Source_Clusters,Dest_Clusters)
    implicit none
    !---Dummy Vars---
    type(ACluster),device,dimension(:,:),allocatable,target::Source_Clusters
    type(ACluster),device,dimension(:,:),allocatable::Dest_Clusters
    integer::NC
    !---Local Vars---
    type(C_DEVPTR)::SrP_Clusters
    type(C_DEVPTR)::DestP_Cluster
    integer::err
    !---Body---
    SrP_Clusters = c_devloc(Source_Clusters)
    DestP_Cluster = c_devloc(Dest_Clusters)


        if(NC .GT. size(Source_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of source clusters:",size(Source_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dest_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of destination clusters:",size(Dest_Clusters), &
                    "less than the copy clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if


    err = cudaMemCpyAsync(DestP_Cluster,SrP_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToDevice)

    return
  end subroutine copyClustersDevToDevAsync2D

  !*****************************************************************
  subroutine copyInClustersSync(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Host to Device(Sychronize)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy
    implicit none
    !---Dummy vars---
    type(Acluster),dimension(:),allocatable,target::HOST_Clusters
    type(Acluster),device,dimension(:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    #ifdef MC_PROFILING
    call Time_Start(T_copyInClustersSync_Start)
    #endif
    !---Body---

    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    ! Way 1
    !DEV_Clusters = HOST_Clusters

    ! Way 2
    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    err = cudaMemcpy(dp_Clusters,hp_Clusters,NC*Get_MemoryConsuming_ClusterType())

    #ifdef MC_PROFILING
    call Time_Accumulate(T_copyInClustersSync_Start,T_copyInClustersSync)
    #endif
    return
  end subroutine copyInClustersSync

  !*****************************************************************
  subroutine copyInClustersSync2D(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Host to Device(Sychronize)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy
    implicit none
    !---Dummy vars---
    type(Acluster),dimension(:,:),allocatable,target::HOST_Clusters
    type(Acluster),device,dimension(:,:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    #ifdef MC_PROFILING
    call Time_Start(T_copyInClustersSync_Start)
    #endif
    !---Body---

    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    ! Way 1
    !DEV_Clusters = HOST_Clusters

    ! Way 2
    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    err = cudaMemcpy(dp_Clusters,hp_Clusters,NC*Get_MemoryConsuming_ClusterType())

    #ifdef MC_PROFILING
    call Time_Accumulate(T_copyInClustersSync_Start,T_copyInClustersSync)
    #endif
    return
  end subroutine copyInClustersSync2D

  !*****************************************************************
  subroutine copyInClustersAsync(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Host to Device(Async)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy
    implicit none
    !---Dummy vars---
    type(Acluster),dimension(:),allocatable,target::HOST_Clusters
    type(Acluster),device,dimension(:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    !---Body---


    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    err = cudaMemcpyAsync(dp_Clusters,hp_Clusters,NC*Get_MemoryConsuming_ClusterType())

    return
  end subroutine copyInClustersAsync

  !*****************************************************************
  subroutine copyInClustersAsync2D(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Host to Device(Async)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy
    implicit none
    !---Dummy vars---
    type(Acluster),dimension(:,:),allocatable,target::HOST_Clusters
    type(Acluster),device,dimension(:,:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    !---Body---


    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyin clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    err = cudaMemcpyAsync(dp_Clusters,hp_Clusters,NC*Get_MemoryConsuming_ClusterType())

    return
  end subroutine copyInClustersAsync2D

  !*****************************************************************
  subroutine copyOutClustersSync(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Device to Host (Sychronize)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy

    !---Dummy vars---
    type(Acluster), dimension(:),allocatable,target::HOST_Clusters
    type(Acluster), device,dimension(:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    #ifdef MC_PROFILING
    call Time_Start(T_copyOutClustersSync_Start)
    #endif

    !---Body---
    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GE. 1) then
        ! Way 1
        !HOST_Clusters = DEV_Clusters

        ! Way 2
        hp_Clusters = c_loc(HOST_Clusters)
        dp_Clusters = c_devloc(DEV_Clusters)

        if(c_associated(hp_Clusters)) then
            err = cudaMemcpy(hp_Clusters,dp_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToHost)
        else
            write(*,*) "clusters copy out failed as the non-associated pointer"
        end if
    end if


    #ifdef MC_PROFILING
    call Time_Accumulate(T_copyOutClustersSync_Start,T_copyOutClustersSync)
    #endif
    return
  end subroutine copyOutClustersSync

  !*****************************************************************
  subroutine copyOutClustersSync2D(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Device to Host (Sychronize)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy

    !---Dummy vars---
    type(Acluster), dimension(:,:),allocatable,target::HOST_Clusters
    type(Acluster), device,dimension(:,:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    #ifdef MC_PROFILING
    call Time_Start(T_copyOutClustersSync_Start)
    #endif

    !---Body---
    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GE. 1) then
        ! Way 1
        !HOST_Clusters = DEV_Clusters

        ! Way 2
        hp_Clusters = c_loc(HOST_Clusters)
        dp_Clusters = c_devloc(DEV_Clusters)

        if(c_associated(hp_Clusters)) then
            err = cudaMemcpy(hp_Clusters,dp_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToHost)
        else
            write(*,*) "clusters copy out failed as the non-associated pointer"
        end if
    end if


    #ifdef MC_PROFILING
    call Time_Accumulate(T_copyOutClustersSync_Start,T_copyOutClustersSync)
    #endif
    return
  end subroutine copyOutClustersSync2D

  !*****************************************************************
  subroutine copyOutClustersAsync(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Device to Host (Asyc)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy

    !---Dummy vars---
    type(Acluster), dimension(:),allocatable,target::HOST_Clusters
    type(Acluster), device,dimension(:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    !---Body---
    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    if(c_associated(hp_Clusters)) then
       err = cudaMemcpyAsync(hp_Clusters,dp_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToHost)
    else
       write(*,*) "clusters copy out failed as the non-associated pointer"
       pause
       stop
    end if

    return
  end subroutine copyOutClustersAsync

  !*****************************************************************
  subroutine copyOutClustersAsync2D(HOST_Clusters,DEV_Clusters,NC)
    !***  PURPOSE:  to copy the Clusters From Device to Host (Asyc)
    !     INPUT:    HOST_Clusters, the clusters array in host
    !               DEV_Clusters , the clusters array in device
    !               NC           , the number of clusters that need to copy

    !---Dummy vars---
    type(Acluster), dimension(:,:),allocatable,target::HOST_Clusters
    type(Acluster), device,dimension(:,:),allocatable::DEV_Clusters
    integer::NC
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_Clusters
    type(C_DEVPTR)::dp_Clusters

    !---Body---
    if(NC .GT. size(HOST_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of host clusters:",size(HOST_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(DEV_Clusters)) then
        write(*,*) "MCPSCUERROR: The size of device clusters:",size(DEV_Clusters), &
                    "less than the copyout clusters size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_Clusters = c_loc(HOST_Clusters)
    dp_Clusters = c_devloc(DEV_Clusters)
    if(c_associated(hp_Clusters)) then
       err = cudaMemcpyAsync(hp_Clusters,dp_Clusters,NC*Get_MemoryConsuming_ClusterType(),cudaMemcpyDeviceToHost)
    else
       write(*,*) "clusters copy out failed as the non-associated pointer"
       pause
       stop
    end if

    return
  end subroutine copyOutClustersAsync2D

  !*****************************************************************
  subroutine copyInGrainSeedsSync(Host_Seeds,Dev_Seeds,NSeed)
    implicit none
    !---Dummy vars---
    type(GrainSeed),dimension(:),allocatable,target::Host_Seeds
    type(GrainSeed),device,dimension(:),allocatable,target::Dev_Seeds
    integer,intent(in)::NSeed
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_GrainSeeds
    type(C_DEVPTR)::dp_GrainSeeds
    !---Body---

    if(NSeed .LE. 0) then
        return
    end if

    if(NSeed .GT. size(Host_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of host seeds array:",size(Host_Seeds), &
                    "less than the copyin seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NSeed .GT. size(Dev_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of device seeds array:",size(Dev_Seeds), &
                    "less than the copyin seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_GrainSeeds = c_loc(Host_Seeds)
    dp_GrainSeeds = c_devloc(Dev_Seeds)

    if(c_associated(hp_GrainSeeds)) then
        err = cudaMemcpy(dp_GrainSeeds,hp_GrainSeeds,NSeed*Get_MemoryConsuming_GrainSeed(),cudaMemcpyHostToDevice)
    else
        write(*,*) "MCPSCUERROR: Grain seeds copyin failed for non-associated pointer in host."
        pause
        stop
    end if

    return
  end subroutine copyInGrainSeedsSync

  !*****************************************************************
  subroutine copyInGrainSeedsAsync(Host_Seeds,Dev_Seeds,NSeed)
    implicit none
    !---Dummy vars---
    type(GrainSeed),dimension(:),allocatable,target::Host_Seeds
    type(GrainSeed),device,dimension(:),allocatable,target::Dev_Seeds
    integer,intent(in)::NSeed
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_GrainSeeds
    type(C_DEVPTR)::dp_GrainSeeds
    !---Body---

    if(NSeed .LE. 0) then
        return
    end if

    if(NSeed .GT. size(Host_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of host seeds array:",size(Host_Seeds), &
                    "less than the copyin seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NSeed .GT. size(Dev_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of device seeds array:",size(Dev_Seeds), &
                    "less than the copyin seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    hp_GrainSeeds = c_loc(Host_Seeds)
    dp_GrainSeeds = c_devloc(Dev_Seeds)

    if(c_associated(hp_GrainSeeds)) then
        err = cudaMemcpyAsync(dp_GrainSeeds,hp_GrainSeeds,NSeed*Get_MemoryConsuming_GrainSeed(),cudaMemcpyHostToDevice)
    else
        write(*,*) "MCPSCUERROR: Grain seeds copyin failed for non-associated pointer in host."
        pause
        stop
    end if

    return
  end subroutine copyInGrainSeedsAsync

  !*****************************************************************
  subroutine copyOutGrainSeedsSync(Host_Seeds,Dev_Seeds,NSeed)
    implicit none
    !---Dummy vars---
    type(GrainSeed),dimension(:),allocatable,target::Host_Seeds
    type(GrainSeed),device,dimension(:),allocatable,target::Dev_Seeds
    integer,intent(in)::NSeed
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_GrainSeeds
    type(C_DEVPTR)::dp_GrainSeeds
    !---Body---

    if(NSeed .LE. 0) then
        return
    end if

    if(NSeed .GT. size(Host_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of host seeds array:",size(Host_Seeds), &
                    "less than the copyout seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NSeed .GT. size(Dev_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of device seeds array:",size(Host_Seeds), &
                    "less than the copyout seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if


    hp_GrainSeeds = c_loc(Host_Seeds)
    dp_GrainSeeds = c_devloc(Dev_Seeds)

    if(c_associated(hp_GrainSeeds)) then
        err = cudaMemcpy(hp_GrainSeeds,dp_GrainSeeds,NSeed*Get_MemoryConsuming_GrainSeed(),cudaMemcpyDeviceToHost)
    else
        write(*,*) "MCPSCUERROR: Grain seeds copyout failed for non-associated pointer in host."
        pause
        stop
    end if

    return
  end subroutine copyOutGrainSeedsSync


  !*****************************************************************
  subroutine copyOutGrainSeedsAsync(Host_Seeds,Dev_Seeds,NSeed)
    implicit none
    !---Dummy vars---
    type(GrainSeed),dimension(:),allocatable,target::Host_Seeds
    type(GrainSeed),device,dimension(:),allocatable,target::Dev_Seeds
    integer,intent(in)::NSeed
    !---Local Vars---
    integer::err
    type(C_PTR)::hp_GrainSeeds
    type(C_DEVPTR)::dp_GrainSeeds
    !---Body---

    if(NSeed .LE. 0) then
        return
    end if

    if(NSeed .GT. size(Host_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of host seeds array:",size(Host_Seeds), &
                    "less than the copyout seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NSeed .GT. size(Dev_Seeds)) then
        write(*,*) "MCPSCUERROR: The size of device seeds array:",size(Host_Seeds), &
                    "less than the copyout seeds size :",NSeed
        write(*,*) "The program would stop."
        pause
        stop
    end if


    hp_GrainSeeds = c_loc(Host_Seeds)
    dp_GrainSeeds = c_devloc(Dev_Seeds)

    if(c_associated(hp_GrainSeeds)) then
        err = cudaMemcpyAsync(hp_GrainSeeds,dp_GrainSeeds,NSeed*Get_MemoryConsuming_GrainSeed(),cudaMemcpyDeviceToHost)
    else
        write(*,*) "MCPSCUERROR: Grain seeds copyout failed for non-associated pointer in host."
        pause
        stop
    end if

    return
  end subroutine copyOutGrainSeedsAsync

  !******************************************
  subroutine copyOutOneDimSync(Host_Array,Dev_Array,NC)
    implicit none
    !---Dummy Vars---
    integer ,dimension(:),allocatable::Host_Array
    integer ,device, dimension(:),allocatable::Dev_Array
    integer,value::NC
    !---Local Vars---
    integer::err

    #ifdef MC_PROFILING
    call Time_Start(T_copyOutActiveIndexSync_Start)
    #endif
    !---Body----
    if(NC .GT. size(Host_Array)) then
        write(*,*) "MCPSCUERROR: The size of host array:",size(Host_Array), &
                    " is less than the copyout  size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dev_Array)) then
        write(*,*) "MCPSCUERROR: The size of device array:",size(Dev_Array), &
                    "less than the copyout size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    !Host_Array = Dev_Array

    err = cudaMemcpy(Host_Array,Dev_Array,NC,cudaMemcpyDeviceToHost)

    #ifdef MC_PROFILING
    call Time_Accumulate(T_copyOutActiveIndexSync_Start,T_copyOutActiveIndexSync)
    #endif
    return
  end subroutine copyOutOneDimSync

  !******************************************
  subroutine copyOutOnDimAsync(Host_Array,Dev_Array,NC)
    implicit none
    !---Dummy Vars---
    integer,value::NC
    integer ,dimension(:),allocatable::Host_Array
    integer ,device, dimension(:),allocatable::Dev_Array
    !---Local Vars---
    integer::err
    !---Body----

    if(NC .GT. size(Host_Array)) then
        write(*,*) "MCPSCUERROR: The size of host  array:",size(Host_Array), &
                    " is less than the copyout  size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dev_Array)) then
        write(*,*) "MCPSCUERROR: The size of device  array:",size(Dev_Array), &
                    "less than the copyout  size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    err = cudaMemcpyAsync(Host_Array,Dev_Array,NC,cudaMemcpyDeviceToHost)

    return
  end subroutine copyOutOnDimAsync

  !******************************************
  subroutine copyInOneDimSync(Host_Array,Dev_Array,NC)
    implicit none
    !---Dummy Vars---
    integer ,dimension(:),allocatable::Host_Array
    integer ,device, dimension(:),allocatable::Dev_Array
    integer,value::NC
    !---Local Vars---
    integer::err
    !---Body----
    if(NC .GT. size(Host_Array)) then
        write(*,*) "MCPSCUERROR: The size of host array:",size(Host_Array), &
                    " is less than the copyin size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dev_Array)) then
        write(*,*) "MCPSCUERROR: The size of device array:",size(Dev_Array), &
                    "less than the copyin size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    err = cudaMemcpy(Dev_Array,Host_Array,NC,cudaMemcpyHostToDevice)

    return
  end subroutine copyInOneDimSync

  !******************************************
  subroutine copyInOneDimAsync(Host_Array,Dev_Array,NC)
    implicit none
    !---Dummy Vars---
    integer,value::NC
    integer ,dimension(:),allocatable::Host_Array
    integer ,device, dimension(:),allocatable::Dev_Array
    !---Local Vars---
    integer::err
    !---Body----
    if(NC .GT. size(Host_Array)) then
        write(*,*) "MCPSCUERROR: The size of hostArray:",size(Host_Array), &
                    " is less than the copyin size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    if(NC .GT. size(Dev_Array)) then
        write(*,*) "MCPSCUERROR: The size of device array:",size(Dev_Array), &
                    "less than the copyin size :",NC
        write(*,*) "The program would stop."
        pause
        stop
    end if

    err = cudaMemcpyAsync(Dev_Array,Host_Array,NC,cudaMemcpyHostToDevice)

    return
  end subroutine copyInOneDimAsync

  !******************************************
  integer function getBlockFilledSize(TNC)
    !***Purpose: to get the block filled array size
    !    TNC   : the original-size
    implicit none
    !---Dummy Vars---
    integer, intent(in)::TNC
    !---Local Vars---
    integer::NB, NBX, NBY


    #ifdef MC_PROFILING
    call Time_Start(T_getBlockFilledSize_Start)
    #endif
    !---Body---
    NB  = (TNC-1)/p_BLOCKSIZE+1
    NBX = min(NB, p_BLOCKDIMX)
    NBY = (NB-1)/NBX+1
    NB  = NBX*NBY

    getBlockFilledSize = NB*p_BLOCKSIZE

    #ifdef MC_PROFILING
    call Time_Accumulate(T_getBlockFilledSize_Start,T_getBlockFilledSize)
    #endif
    return
  end function getBlockFilledSize

end module MCMF_Utilities_GPU
