!*********************************************************************************!
!--- Description:
!--- Author : Lei Zhai, Insti. of Nucle. Sci. and Tech., Sichuan University
!--- Email : zhaileiytp@163.com
!--- data: From 2017-09 to 2021-12
!--- License: MIT License (There are no limitation for anyone to use/modify/sale of this code, be happy to use this code)
!--- Please ref "Lei Zhai, Chaoqiong Ma, Jiechao Cui and Qing Hou, GPU-based acceleration of Monte Carlo simulations for migration-coalescence evolution of gas bubbles in materials
!---                        Modelling Simul. Mater. Sci. Eng. 2019. 27 055008,https://iopscience.iop.org/article/10.1088/1361-651X/ab1d14
!*********************************************************************************!
!
!  MCLIB_GLOBAL_VARIABLES_GPU.F90
!
!  Free-Format Fortran Source File
!  Generated by PGI Visual Fortran(R)
!  9/25/2017 10:14:10 PM
!
module MFLIB_GLOBAL_GPU

  use cudafor
  use CudaRandomC2F_M
  use MFLIB_GLOBAL
  use MFLIB_TYPEDEF_SIMULATIONBOXARRAY_GPU
  #ifdef MC_PROFILING
  use MCLIB_TimeProfile
  #endif

  implicit none
  !--------------Global vars in GPU--------------------
  integer,dimension(:),allocatable::m_Running_Devices             !record the table about which devices were occupied
  integer::m_NTotal_Device                                        !total device in system


  contains

  !********************************************************
  subroutine Init_Device_Setting(ID_Device,n_Device)
    !*** PURPOSE: to init the device setting
    !---Dummy vars---
    integer::ID_Device               !Index of the indicated devices
    integer::n_Device                !number of devices to use
    !---Local vars---
    integer::I,err

    #ifdef MC_PROFILING
    call Time_Start(T_Init_Device_Setting_Start)
    #endif
    !---Body---
    err = cudaGetDeviceCount(m_NTotal_Device)

    if(m_NTotal_Device .LT. 0) then
      write(*,*) "There were not devices in system!"
      stop
    end if

    !initial the record about which devices were occupied
    call AllocateArray_Host(m_Running_Devices,m_NTotal_Device,"m_Running_Devices")
    m_Running_Devices = -1

    !adjust the user-setting of devices
    if(ID_Device .GT. (m_NTotal_Device-1) ) then
        write(*,*) "MDPSCU Error: the ID of the first GPU is larger than the available value."
        write(*,fmt="(A,1x,I3)") "              the number of GPUs on this machine is", m_NTotal_Device
        stop
    end if

    if(n_Device .GT. (m_NTotal_Device - ID_Device)) then
        write(*,*) "MDPSCU Error: the number of GPUs to be used is larger than the available value."
        write(*,fmt="(A,1x,I3)") "              the number of GPUs on this machine", m_NTotal_Device
        write(*,fmt="(A,1x,I3)") "              the ID of the first GPU is", ID_Device
        write(*,fmt="(A,1x,I3)") "              the number of GPUs to be used cannot be larger than",m_NTotal_Device - ID_Device
        stop
    end if

    if(ID_Device .LT. 0) then
        write(*,*) "MDPSCU Error: the ID of start GPU is litter than zero.",ID_Device
        stop
    end if

    if(n_Device .LE. 0) then
        write(*,*) "MDPSCU Error: the number of GPUs to be used is zero.",n_Device
        stop
    end if

    !record the list about which devices were occupied
    m_Running_Devices(1) = ID_Device

    DO I=2,n_Device
        m_Running_Devices(I) = m_Running_Devices(I-1) + 1
    END DO

    err = cudaSetDevice(m_Running_Devices(1))

    #ifdef MC_PROFILING
    call Time_Accumulate(T_Init_Device_Setting_Start,T_Init_Device_Setting)
    #endif

    return
  end subroutine Init_Device_Setting


!  !*******************************************************************
!  subroutine Initital_Global_Variables_GPU(Host_Boxes,Host_SimuCtrlParam,Dev_Boxes)
!    !*** Purpose: to initial some vars and array for growth fixbox in GPU
!    implicit none
!    !---dummy Vars----
!    type(SimulationBoxes)::Host_Boxes
!    type(SimulationCtrlParam)::Host_SimuCtrlParam
!    type(SimulationBoxes_GPU)::Dev_Boxes
!    !---Local Vars----
!    integer::MultiBox
!    integer::TotalSize
!    integer::err
!    !---Body----
!
!    MultiBox = Host_SimuCtrlParam%MultiBox
!
!    if(Host_Boxes%m_BoxesInfo%SEVirtualIndexBox(MultiBox,2) .GT. 0) then
!        TotalSize = Host_Boxes%m_BoxesInfo%SEVirtualIndexBox(MultiBox,2) - Host_Boxes%m_BoxesInfo%SEVirtualIndexBox(1,1) + 1
!    else
!        TotalSize = 0
!    end if
!
!    call CleanSimulationBoxes_GPU(Dev_Boxes)
!
!    call Dev_Boxes%InitSimulationBoxes_Dev(Host_Boxes,Host_SimuCtrlParam)
!
!    call Dev_Boxes%CopyInBoxesArrayFromHost(Host_Boxes,TotalSize,IfCpyNL=.false.)
!
!
!    return
!  end subroutine Initital_Global_Variables_GPU

end module MFLIB_GLOBAL_GPU
